### ISSUE TITLE
Validate all colors props

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/vue-rocker-switch#1]
We need to make sure that the colors passed by props are valid colors: 
Hex: `#ff0000` (red)
RGB: `rgb(0, 255, 0)` (green)
RGBA: `rgba(0, 0, 255, 0.3)` (blue with opacity)
HSL: `hsl(120, 100%, 75%)` (light green)
HSLA: `hsla(120, 100%, 25%, 0.3)` (dark green with opacity)
The 140 colors predefined by the browsers like red, blue, white, etc.

Valid
```vue
 <rocker-switch active-color="rgba(221,22,112,0.3)" />
```

Invalid
```vue
 <rocker-switch active-color="foobar" />
```

**Comment by vyzaldysanchez** [comment]
Do we have a more detailed description about this issue? @DannyFeliz

**Comment by DannyFeliz** [comment]
@vyzaldysanchez I updated the description.

**Comment by vyzaldysanchez** [comment]
I'll be working on this. I'm planning on using [this library](https://github.com/meodai/color-names) as a colors list reference. Any thoughts @DannyFeliz ?

**Comment by DannyFeliz** [comment]
@vyzaldysanchez LGTM, I know some famous ones in case you want to checkout it out.
[color-string](https://www.npmjs.com/package/color-string)
[color](https://www.npmjs.com/package/color)

**Comment by vyzaldysanchez** [comment]
I added #2 as a possible solution. Please take a look @DannyFeliz

I wonder if you'd like to add test coverage to the component.

**Comment by DannyFeliz** [comment]
> I added #2 as a possible solution. Please take a look @DannyFeliz
> 
> I wonder if you'd like to add test coverage to the component.

Sure, they are always welcome.

**Comment by vyzaldysanchez** [comment]
Will you close this issue now and create a new one for test coverage or will you create a new issue? @DannyFeliz

**Comment by vyzaldysanchez** [comment]
Just saw you closed it. Nice.
