### ISSUE TITLE
Changing the font size

### ISSUE THREAD

**Issue by mreduar** [DannyFeliz/vue-rocker-switch#37]
Hi, your component is great. Thank you so much for sharing!

I see that there is only one option to change the size of the switch, however there is no option to change the size of the text inside. Since changing the word for a longer one it doesn't look right (complete), try changing it with the styles but it resizes the whole component.

https://codesandbox.io/s/vue-rocker-switch-demo-o97cu

**Comment by DannyFeliz** [comment]
Hey @MrEdua, thank you for the code example.

I will take a look at it this weekend.
